name: Build WAR, Push to ECR and Deploy 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: [self-hosted, dev]

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID:  983426484039
      ECR_REPOSITORY: myrepo
      IMAGE_TAG: latest
      ECR_REGISTRY: 983426484039.dkr.ecr.ap-south-1.amazonaws.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build WAR using build.sh
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image using Dockerfile
        run: |
          docker build -t \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image to ECR
        run: |
          docker push \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f svc.yml
